version: '3'

services:
  web:
    build:  demopy/
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=jokesdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

  angular:
      build: angular/demo1/      
      ports:
        - "80:3000"